version: "3.9"

services:
  web:
    build: .
    container_name: web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app
      - uploads:/tmp/uploads        # <-- SHARE THIS

  worker:
    build: .
    container_name: worker
    command: celery -A tasks.celery_app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app
      - uploads:/tmp/uploads        # <-- SHARE THIS

  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: acme

volumes:
  uploads:                        # <-- DECLARE SHARED VOLUME
